sudo: false
language: node_js
node_js:
- '0.10'
before_install:
- "export DISPLAY=:99.0"
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
before_script:
- npm install jpm get-firefox -g
- cd ..
- get-firefox -p linux -t firefox.tar.bz2
- tar -xjf firefox.tar.bz2
- cd $TRAVIS_BUILD_DIR
script:
- export JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/../firefox/firefox
- jpm test -v
deploy:
  provider: npm
  email: martin@humanoids.be
  on:
    tags: true
  api_key:
    secure: PcV3fmaK5KjZMZTE7dP2bQd6PZlAbVMjRcuCADLYSesTLNTAAI+GZvpMfI7EuTRZrnGxHWnq9MjV6fkARzRM+uEBRSixaJk1f35HQwpWbn+UShQkACbWXBde70NOwduHIJfxwzHwl9ZdmoAtAM3L51h6rkgWyF7RwPOA9UYt1+4=
