sudo: false
language: node_js
addons:
  firefox: latest
env:
  global:
  - DISPLAY=:99.0
  - JPM_FIREFOX_BINARY=/usr/local/bin/firefox
before_install:
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g jpm
script:
- jpm test -v
deploy:
  provider: npm
  email: martin@humanoids.be
  on:
    tags: true
  api_key:
    secure: PcV3fmaK5KjZMZTE7dP2bQd6PZlAbVMjRcuCADLYSesTLNTAAI+GZvpMfI7EuTRZrnGxHWnq9MjV6fkARzRM+uEBRSixaJk1f35HQwpWbn+UShQkACbWXBde70NOwduHIJfxwzHwl9ZdmoAtAM3L51h6rkgWyF7RwPOA9UYt1+4=
